; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=microblazeel < %s | FileCheck %s
; REQUIRES: microblaze-registered-target
; The delay slot filler hoists rtsd before a single trailing instruction,
; placing it in rtsd's delay slot.

define i32 @add_i32(i32 %a, i32 %b) {
; CHECK-LABEL: add_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    addk r3, r5, r6
  %r = add i32 %a, %b
  ret i32 %r
}

define i32 @sub_i32(i32 %a, i32 %b) {
; CHECK-LABEL: sub_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    rsubk r3, r6, r5
  %r = sub i32 %a, %b
  ret i32 %r
}

define i32 @mul_i32(i32 %a, i32 %b) {
; CHECK-LABEL: mul_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    mul r3, r5, r6
  %r = mul i32 %a, %b
  ret i32 %r
}

define i32 @and_i32(i32 %a, i32 %b) {
; CHECK-LABEL: and_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    and r3, r5, r6
  %r = and i32 %a, %b
  ret i32 %r
}

define i32 @or_i32(i32 %a, i32 %b) {
; CHECK-LABEL: or_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    or r3, r5, r6
  %r = or i32 %a, %b
  ret i32 %r
}

define i32 @xor_i32(i32 %a, i32 %b) {
; CHECK-LABEL: xor_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    xor r3, r5, r6
  %r = xor i32 %a, %b
  ret i32 %r
}

define i32 @add_imm(i32 %a) {
; CHECK-LABEL: add_imm:
; CHECK:       # %bb.0:
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    addik r3, r5, 42
  %r = add i32 %a, 42
  ret i32 %r
}

; With two instructions before the return, only the last one fills the slot.
define i32 @three_args(i32 %a, i32 %b, i32 %c) {
; CHECK-LABEL: three_args:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addk r3, r5, r6
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    addk r3, r3, r7
  %t = add i32 %a, %b
  %r = add i32 %t, %c
  ret i32 %r
}
