; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=microblazeel-unknown-linux-gnu %s -o - | FileCheck %s
; REQUIRES: microblaze-registered-target;
; Verify that cmpxchg and atomicrmw lower to LWX/SWX LL/SC loops.
; LWX sets the hardware reservation; SWX stores conditionally and sets
; MSR[C]=0 on success / MSR[C]=1 on failure (UG984 §5, opcodes 0x32/0x36).

define i32 @test_cmpxchg(ptr %p, i32 %expected, i32 %desired) {
; CHECK-LABEL: test_cmpxchg:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB0_1: # %cmpxchg.start
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    #APP
; CHECK-NEXT:    lwx r3, r5, r0
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    rsubk r4, r3, r6
; CHECK-NEXT:    bnei r4, .LBB0_3
; CHECK-NEXT:  .LBB0_2: # %cmpxchg.trystore
; CHECK-NEXT:    # in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    #APP
; CHECK-NEXT:    swx r7, r5, r0
; CHECK-EMPTY:
; CHECK-NEXT:    mfs r4, 1
; CHECK-EMPTY:
; CHECK-NEXT:    andi r4, r4, 4
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    bneid r4, .LBB0_1
; CHECK-NEXT:    nop
; CHECK-NEXT:  .LBB0_3: # %cmpxchg.end
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    nop
entry:
  %res = cmpxchg ptr %p, i32 %expected, i32 %desired seq_cst seq_cst
  %val = extractvalue { i32, i1 } %res, 0
  ret i32 %val
}

define i1 @test_cmpxchg_bool(ptr %p, i32 %expected, i32 %desired) {
; CHECK-LABEL: test_cmpxchg_bool:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB1_1: # %cmpxchg.start
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    #APP
; CHECK-NEXT:    lwx r3, r5, r0
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    rsubk r3, r3, r6
; CHECK-NEXT:    bnei r3, .LBB1_4
; CHECK-NEXT:  .LBB1_2: # %cmpxchg.trystore
; CHECK-NEXT:    # in Loop: Header=BB1_1 Depth=1
; CHECK-NEXT:    #APP
; CHECK-NEXT:    swx r7, r5, r0
; CHECK-EMPTY:
; CHECK-NEXT:    mfs r3, 1
; CHECK-EMPTY:
; CHECK-NEXT:    andi r3, r3, 4
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    bneid r3, .LBB1_1
; CHECK-NEXT:    nop
; CHECK-NEXT:  .LBB1_3: # %cmpxchg.success
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    addik r3, r0, 1
; CHECK-NEXT:  .LBB1_4: # %cmpxchg.failure
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    addik r3, r0, 0
entry:
  %res = cmpxchg ptr %p, i32 %expected, i32 %desired seq_cst seq_cst
  %ok = extractvalue { i32, i1 } %res, 1
  ret i1 %ok
}

define i32 @test_atomicrmw_add(ptr %p, i32 %val) {
; CHECK-LABEL: test_atomicrmw_add:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB2_1: # %atomicrmw.start
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    #APP
; CHECK-NEXT:    lwx r3, r5, r0
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    addk r4, r3, r6
; CHECK-NEXT:    #APP
; CHECK-NEXT:    swx r4, r5, r0
; CHECK-EMPTY:
; CHECK-NEXT:    mfs r7, 1
; CHECK-EMPTY:
; CHECK-NEXT:    andi r7, r7, 4
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    bneid r7, .LBB2_1
; CHECK-NEXT:    nop
; CHECK-NEXT:  .LBB2_2: # %atomicrmw.end
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    nop
entry:
  %old = atomicrmw add ptr %p, i32 %val seq_cst
  ret i32 %old
}

define i32 @test_atomicrmw_xchg(ptr %p, i32 %val) {
; CHECK-LABEL: test_atomicrmw_xchg:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB3_1: # %atomicrmw.start
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    #APP
; CHECK-NEXT:    lwx r3, r5, r0
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    #APP
; CHECK-NEXT:    swx r6, r5, r0
; CHECK-EMPTY:
; CHECK-NEXT:    mfs r4, 1
; CHECK-EMPTY:
; CHECK-NEXT:    andi r4, r4, 4
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    bneid r4, .LBB3_1
; CHECK-NEXT:    nop
; CHECK-NEXT:  .LBB3_2: # %atomicrmw.end
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    nop
entry:
  %old = atomicrmw xchg ptr %p, i32 %val seq_cst
  ret i32 %old
}
