; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=microblazeel < %s | FileCheck %s
; REQUIRES: microblaze-registered-target
; max(a, b): uses cmp + bgei.
; cmp rD,rA,rB sets bit31=1 when rA>rB; bgei branches when rD>=0 (i.e. a<=b).
; The delay slot filler cannot hoist 'cmp' into bgeid's delay slot because cmp
; defines r3 which bgeid also reads (conservative backedge guard), so bgeid is
; converted to the no-delay-slot form bgei.
define i32 @max(i32 %a, i32 %b) {
; CHECK-LABEL: max:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cmp r3, r5, r6
; CHECK-NEXT:    bgei r3, .LBB0_2
; CHECK-NEXT:  .LBB0_1: # %then
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    addk r3, r5, r0
; CHECK-NEXT:  .LBB0_2: # %else
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    addk r3, r6, r0
  %cmp = icmp sgt i32 %a, %b
  br i1 %cmp, label %then, label %else
then:
  ret i32 %a
else:
  ret i32 %b
}

; min(a, b): uses cmp + blei.
define i32 @min(i32 %a, i32 %b) {
; CHECK-LABEL: min:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cmp r3, r6, r5
; CHECK-NEXT:    bgei r3, .LBB1_2
; CHECK-NEXT:  .LBB1_1: # %then
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    addk r3, r5, r0
; CHECK-NEXT:  .LBB1_2: # %else
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    addk r3, r6, r0
  %cmp = icmp slt i32 %a, %b
  br i1 %cmp, label %then, label %else
then:
  ret i32 %a
else:
  ret i32 %b
}

; Conditional back-edge loop with phi.
; cmp r, next, n → bgtid fires when next < n (bit31=0, n-next>0); delayed form fills NOP.
define i32 @loop_phi(i32 %n) {
; CHECK-LABEL: loop_phi:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addik r3, r0, 0
; CHECK-NEXT:  .LBB2_1: # %loop
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    addik r3, r3, 1
; CHECK-NEXT:    cmp r4, r5, r3
; CHECK-NEXT:    bltid r4, .LBB2_1
; CHECK-NEXT:    nop
; CHECK-NEXT:  .LBB2_2: # %done
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    nop
entry:
  br label %loop
loop:
  %i = phi i32 [ 0, %entry ], [ %next, %loop ]
  %next = add i32 %i, 1
  %cmp = icmp slt i32 %next, %n
  br i1 %cmp, label %loop, label %done
done:
  ret i32 %next
}
