; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=microblazeel -mattr=+pattern-compare -verify-machineinstrs %s -o - | FileCheck %s
; REQUIRES: microblaze-registered-target

; Tests for MicroBlazeDelaySlotFiller::hoistCopyToDelaySlot, which recognises a
; register copy (addk rX, rY, R0) followed by zero or more non-conflicting
; instructions and a D-form conditional backward branch, then:
;   1. Replaces every USE of rX in the intervening instructions with rY.
;   2. Moves the addk into the delay slot of the branch (bundle).
;
; The qsort partition-scan loop is the canonical trigger: at the outer-loop
; back-edge the register allocator emits two addk copies for the partition
; bounds (l, r), then a cmpu, then a bgeid targeting the inner-loop header
; (a lower-numbered block).  The first addk is hoisted; the second addk stays
; and the cmpu's source register is rewritten from rX to rY.

; ── Source C equivalent ──────────────────────────────────────────────────────
; void qs(int *lo, int *hi);   // recursive quicksort partition
; Declared below as @qs with a fastcc calling convention.

; ── Pre-hoisting MIR (bb.7, inner=bb.5 Depth=2, after block-placement): ───────
;
;   $r6  = ADDK $r7, $r0       ; r6  = r7  (hi-side bound copy)
;   $r25 = ADDK $r5, $r0       ; r25 = r5  (lo-side bound copy)
;   $r4  = CMPU $r25, $r6      ; compare bounds
;   BGEID $r4, %bb.5           ; backward → fire hoistCopyToDelaySlot
;
; After hoisting (the first addk moves to the delay slot; r6→r7 substituted):
;   $r25 = ADDK $r5, $r0       ; second addk stays
;   $r4  = CMPU $r25, $r7      ; rX→rY substitution: r6 → r7
;   BGEID $r4, %bb.5 { $r6 = ADDK $r7, $r0 }  ; first addk in delay slot
;
; ── FileCheck structure ───────────────────────────────────────────────────────
;
; There are three backward bgeid branches in qs():
;   LBB*_8:  cmpu+bgeid with NOP  (no addk to hoist — enters as-is)
;   LBB*_9:  addk+cmpu+bgeid+addk (hoistCopyToDelaySlot fired)
;   LBB*_10: cmpu+bgeid with NOP  (no addk to hoist — enters as-is)
;
;
; ── Negative 1: first bgeid, NOP in delay slot (no addk to hoist) ────────────
;
; ── Positive: after the NOP block, hoistCopyToDelaySlot fires ────────────────
; The cmpu immediately precedes the bgeid, and [[SRC]] (the substituted
; register) must appear as the last source of the cmpu AND as the source
; of the delay-slot addk — proving the rX→rY substitution was applied.
;
; ── Negative 2: next bgeid, NOP in delay slot (no addk to hoist) ─────────────

; ── IR — qs() partition function ─────────────────────────────────────────────

define internal fastcc void @qs(ptr noundef %0, ptr noundef %1) #0 {
; CHECK-LABEL: qs:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addik r1, r1, -24
; CHECK-NEXT:    swi r15, r1, 0
; CHECK-NEXT:    swi r19, r1, 20
; CHECK-NEXT:    swi r22, r1, 16
; CHECK-NEXT:    swi r23, r1, 12
; CHECK-NEXT:    swi r24, r1, 8
; CHECK-NEXT:    addk r19, r6, r0
; CHECK-NEXT:    addk r24, r5, r0
; CHECK-NEXT:    addik r22, r0, 3
; CHECK-NEXT:    addik r23, r0, 2
; CHECK-NEXT:    swi r25, r1, 4
; CHECK-NEXT:    bri .LBB0_2
; CHECK-NEXT:  .LBB0_1: # in Loop: Header=BB0_2 Depth=1
; CHECK-NEXT:    cmpu r3, r19, r25
; CHECK-NEXT:    bgeid r3, .LBB0_12
; CHECK-NEXT:    addk r24, r25, r0
; CHECK-NEXT:  .LBB0_2: # =>This Loop Header: Depth=1
; CHECK-NEXT:    # Child Loop BB0_5 Depth 2
; CHECK-NEXT:    # Child Loop BB0_7 Depth 3
; CHECK-NEXT:    cmpu r3, r19, r24
; CHECK-NEXT:    bgei r3, .LBB0_12
; CHECK-NEXT:  .LBB0_3: # in Loop: Header=BB0_2 Depth=1
; CHECK-NEXT:    rsubk r5, r24, r19
; CHECK-NEXT:    bralid r15, __ashrsi3
; CHECK-NEXT:    addk r6, r22, r0
; CHECK-NEXT:    addk r5, r3, r0
; CHECK-NEXT:    bralid r15, __ashlsi3
; CHECK-NEXT:    addk r6, r23, r0
; CHECK-NEXT:    lw r3, r24, r3
; CHECK-NEXT:    addk r25, r24, r0
; CHECK-NEXT:    addk r6, r19, r0
; CHECK-NEXT:    bri .LBB0_5
; CHECK-NEXT:  .LBB0_4: # in Loop: Header=BB0_5 Depth=2
; CHECK-NEXT:    addik r6, r7, -4
; CHECK-NEXT:    swi r8, r5, 0
; CHECK-NEXT:    swi r4, r7, 0
; CHECK-NEXT:    cmpu r4, r25, r6
; CHECK-NEXT:    blti r4, .LBB0_10
; CHECK-NEXT:  .LBB0_5: # Parent Loop BB0_2 Depth=1
; CHECK-NEXT:    # => This Loop Header: Depth=2
; CHECK-NEXT:    # Child Loop BB0_7 Depth 3
; CHECK-NEXT:    lwi r4, r25, 0
; CHECK-NEXT:    cmp r5, r3, r4
; CHECK-NEXT:    bltid r5, .LBB0_5
; CHECK-NEXT:    addik r25, r25, 4
; CHECK-NEXT:  .LBB0_6: # %.preheader
; CHECK-NEXT:    # in Loop: Header=BB0_5 Depth=2
; CHECK-NEXT:    addik r7, r6, 4
; CHECK-NEXT:    addik r5, r25, -4
; CHECK-NEXT:  .LBB0_7: # Parent Loop BB0_2 Depth=1
; CHECK-NEXT:    # Parent Loop BB0_5 Depth=2
; CHECK-NEXT:    # => This Inner Loop Header: Depth=3
; CHECK-NEXT:    lwi r8, r7, -4
; CHECK-NEXT:    cmp r6, r8, r3
; CHECK-NEXT:    bltid r6, .LBB0_7
; CHECK-NEXT:    addik r7, r7, -4
; CHECK-NEXT:  .LBB0_8: # in Loop: Header=BB0_5 Depth=2
; CHECK-NEXT:    cmpu r6, r5, r7
; CHECK-NEXT:    bgeid r6, .LBB0_4
; CHECK-NEXT:    nop
; CHECK-NEXT:  .LBB0_9: # in Loop: Header=BB0_5 Depth=2
; CHECK-NEXT:    addk r25, r5, r0
; CHECK-NEXT:    cmpu r4, r25, r7
; CHECK-NEXT:    bgeid r4, .LBB0_5
; CHECK-NEXT:    addk r6, r7, r0
; CHECK-NEXT:  .LBB0_10: # in Loop: Header=BB0_2 Depth=1
; CHECK-NEXT:    cmpu r3, r6, r24
; CHECK-NEXT:    bgeid r3, .LBB0_1
; CHECK-NEXT:    nop
; CHECK-NEXT:  .LBB0_11: # in Loop: Header=BB0_2 Depth=1
; CHECK-NEXT:    bralid r15, qs
; CHECK-NEXT:    addk r5, r24, r0
; CHECK-NEXT:    bri .LBB0_1
; CHECK-NEXT:  .LBB0_12:
; CHECK-NEXT:    lwi r25, r1, 4
; CHECK-NEXT:    lwi r24, r1, 8
; CHECK-NEXT:    lwi r23, r1, 12
; CHECK-NEXT:    lwi r22, r1, 16
; CHECK-NEXT:    lwi r19, r1, 20
; CHECK-NEXT:    lwi r15, r1, 0
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    addik r1, r1, 24
  %3 = ptrtoint ptr %1 to i32
  br label %4

4:
  %5 = phi ptr [ %0, %2 ], [ %31, %36 ]
  %6 = icmp ult ptr %5, %1
  br i1 %6, label %7, label %38

7:
  %8 = ptrtoint ptr %5 to i32
  %9 = sub i32 %3, %8
  %10 = ashr i32 %9, 3
  %11 = getelementptr inbounds [4 x i8], ptr %5, i32 %10
  %12 = load i32, ptr %11, align 4
  br label %13

13:
  %14 = phi ptr [ %5, %7 ], [ %31, %29 ]
  %15 = phi ptr [ %1, %7 ], [ %30, %29 ]
  br label %16

16:
  %17 = phi ptr [ %20, %16 ], [ %14, %13 ]
  %18 = load i32, ptr %17, align 4
  %19 = icmp slt i32 %18, %12
  %20 = getelementptr inbounds nuw i8, ptr %17, i32 4
  br i1 %19, label %16, label %21

21:
  %22 = phi ptr [ %25, %21 ], [ %15, %16 ]
  %23 = load i32, ptr %22, align 4
  %24 = icmp sgt i32 %23, %12
  %25 = getelementptr inbounds i8, ptr %22, i32 -4
  br i1 %24, label %21, label %26

26:
  %27 = icmp ugt ptr %17, %22
  br i1 %27, label %29, label %28

28:
  store i32 %23, ptr %17, align 4
  store i32 %18, ptr %22, align 4
  br label %29

29:
  %30 = phi ptr [ %25, %28 ], [ %22, %26 ]
  %31 = phi ptr [ %20, %28 ], [ %17, %26 ]
  %32 = icmp ugt ptr %31, %30
  br i1 %32, label %33, label %13

33:
  %34 = icmp ugt ptr %30, %5
  br i1 %34, label %35, label %36

35:
  tail call fastcc void @qs(ptr noundef %5, ptr noundef nonnull %30)
  br label %36

36:
  %37 = icmp ult ptr %31, %1
  br i1 %37, label %4, label %38

38:
  ret void
}

attributes #0 = { nofree noinline nosync nounwind memory(argmem: readwrite)
                  "target-features"="+pattern-compare" }
