; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; delay-slot-pipeline.ll — the branch delay-slot filler is shared across the two
; MicroBlaze pipeline configurations.
;
; MicroBlaze exposes the same architectural one-instruction delay slot on both
; the C_AREA_OPTIMIZED=0 5-stage performance pipeline (default → the
; MicroBlazeSpeedModel scheduling model) and the C_AREA_OPTIMIZED=1 3-stage
; area pipeline (+area-optimized → MicroBlazeAreaModel).  Only scheduling
; latency differs between them (see MicroBlazeSchedule.td and the "mca
; sched-pipeline" checks); the delay-slot filler itself is pipeline-independent
; and runs identically under either model.  The two RUN lines below drive the
; same generic filler under each SchedMachineModel and expect the same fills.
;
; RUN: llc -mtriple=microblazeel-unknown-elf < %s | FileCheck %s
; RUN: llc -mtriple=microblazeel-unknown-elf -mattr=+area-optimized < %s | FileCheck %s
; REQUIRES: microblaze-registered-target
; The value-producing add fills the rtsd (return) delay slot on both pipelines.

define i32 @add_ret(i32 %a, i32 %b) {
; CHECK-LABEL: add_ret:
; CHECK:       # %bb.0:
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    addk r3, r5, r6
  %s = add i32 %a, %b
  ret i32 %s
}

; A load is safe in the delay slot (2-cycle load-to-use latency is covered by
; the branch stage on both pipelines); it fills the rtsd slot on both.

define i32 @load_ret(ptr %p) {
; CHECK-LABEL: load_ret:
; CHECK:       # %bb.0:
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    lwi r3, r5, 0
  %v = load i32, ptr %p
  ret i32 %v
}
