; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=microblazeel -mattr=+hard-float,+float-convert -O2 < %s \
; RUN:   | FileCheck %s --check-prefix=HW
; RUN: llc -mtriple=microblazeel -O2 < %s \
; RUN:   | FileCheck %s --check-prefix=SOFT
; REQUIRES: microblaze-registered-target
; Float arithmetic and conversion instructions (UG984 §5 opcode 0x16).
; +hard-float selects FPU instructions; without it, compiler-rt libcalls are used.
; +float-convert enables hardware flt/fint conversion instructions.

define float @fadd_test(float %a, float %b) {
;
; HW-LABEL: fadd_test:
; HW:       # %bb.0:
; HW-NEXT:    rtsd r15, 8
; HW-NEXT:    fadd r3, r5, r6
;
; SOFT-LABEL: fadd_test:
; SOFT:       # %bb.0:
; SOFT-NEXT:    addik r1, r1, -8
; SOFT-NEXT:    swi r15, r1, 4
; SOFT-NEXT:    bralid r15, __addsf3
; SOFT-NEXT:    nop
; SOFT-NEXT:    lwi r15, r1, 4
; SOFT-NEXT:    rtsd r15, 8
; SOFT-NEXT:    addik r1, r1, 8
  %r = fadd float %a, %b
  ret float %r
}

; frsub rD, rA, rB = rB - rA; operands swapped to compute a - b.
define float @fsub_test(float %a, float %b) {
;
; HW-LABEL: fsub_test:
; HW:       # %bb.0:
; HW-NEXT:    rtsd r15, 8
; HW-NEXT:    frsub r3, r6, r5
;
; SOFT-LABEL: fsub_test:
; SOFT:       # %bb.0:
; SOFT-NEXT:    addik r1, r1, -8
; SOFT-NEXT:    swi r15, r1, 4
; SOFT-NEXT:    bralid r15, __subsf3
; SOFT-NEXT:    nop
; SOFT-NEXT:    lwi r15, r1, 4
; SOFT-NEXT:    rtsd r15, 8
; SOFT-NEXT:    addik r1, r1, 8
  %r = fsub float %a, %b
  ret float %r
}

define float @fmul_test(float %a, float %b) {
;
; HW-LABEL: fmul_test:
; HW:       # %bb.0:
; HW-NEXT:    rtsd r15, 8
; HW-NEXT:    fmul r3, r5, r6
;
; SOFT-LABEL: fmul_test:
; SOFT:       # %bb.0:
; SOFT-NEXT:    addik r1, r1, -8
; SOFT-NEXT:    swi r15, r1, 4
; SOFT-NEXT:    bralid r15, __mulsf3
; SOFT-NEXT:    nop
; SOFT-NEXT:    lwi r15, r1, 4
; SOFT-NEXT:    rtsd r15, 8
; SOFT-NEXT:    addik r1, r1, 8
  %r = fmul float %a, %b
  ret float %r
}

define float @fdiv_test(float %a, float %b) {
;
; HW-LABEL: fdiv_test:
; HW:       # %bb.0:
; HW-NEXT:    rtsd r15, 8
; HW-NEXT:    fdiv r3, r5, r6
;
; SOFT-LABEL: fdiv_test:
; SOFT:       # %bb.0:
; SOFT-NEXT:    addik r1, r1, -8
; SOFT-NEXT:    swi r15, r1, 4
; SOFT-NEXT:    bralid r15, __divsf3
; SOFT-NEXT:    nop
; SOFT-NEXT:    lwi r15, r1, 4
; SOFT-NEXT:    rtsd r15, 8
; SOFT-NEXT:    addik r1, r1, 8
  %r = fdiv float %a, %b
  ret float %r
}

define float @fsqrt_test(float %a) {
;
; HW-LABEL: fsqrt_test:
; HW:       # %bb.0:
; HW-NEXT:    rtsd r15, 8
; HW-NEXT:    fsqrt r3, r5
;
; SOFT-LABEL: fsqrt_test:
; SOFT:       # %bb.0:
; SOFT-NEXT:    addik r1, r1, -8
; SOFT-NEXT:    swi r15, r1, 4
; SOFT-NEXT:    bralid r15, sqrtf
; SOFT-NEXT:    nop
; SOFT-NEXT:    lwi r15, r1, 4
; SOFT-NEXT:    rtsd r15, 8
; SOFT-NEXT:    addik r1, r1, 8
  %r = call float @llvm.sqrt.f32(float %a)
  ret float %r
}

define float @sint_to_fp_test(i32 %a) {
;
; HW-LABEL: sint_to_fp_test:
; HW:       # %bb.0:
; HW-NEXT:    rtsd r15, 8
; HW-NEXT:    flt r3, r5
;
; SOFT-LABEL: sint_to_fp_test:
; SOFT:       # %bb.0:
; SOFT-NEXT:    addik r1, r1, -8
; SOFT-NEXT:    swi r15, r1, 4
; SOFT-NEXT:    bralid r15, __floatsisf
; SOFT-NEXT:    nop
; SOFT-NEXT:    lwi r15, r1, 4
; SOFT-NEXT:    rtsd r15, 8
; SOFT-NEXT:    addik r1, r1, 8
  %r = sitofp i32 %a to float
  ret float %r
}

define i32 @fp_to_sint_test(float %a) {
;
; HW-LABEL: fp_to_sint_test:
; HW:       # %bb.0:
; HW-NEXT:    rtsd r15, 8
; HW-NEXT:    fint r3, r5
;
; SOFT-LABEL: fp_to_sint_test:
; SOFT:       # %bb.0:
; SOFT-NEXT:    addik r1, r1, -8
; SOFT-NEXT:    swi r15, r1, 4
; SOFT-NEXT:    bralid r15, __fixsfsi
; SOFT-NEXT:    nop
; SOFT-NEXT:    lwi r15, r1, 4
; SOFT-NEXT:    rtsd r15, 8
; SOFT-NEXT:    addik r1, r1, 8
  %r = fptosi float %a to i32
  ret i32 %r
}

declare float @llvm.sqrt.f32(float)
