; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=microblazeel -mattr=+hard-float,+float-convert -O2 < %s \
; RUN:   | FileCheck %s --check-prefix=HW
; RUN: llc -mtriple=microblazeel -O2 < %s \
; RUN:   | FileCheck %s --check-prefix=SOFT
; REQUIRES: microblaze-registered-target
; Float comparisons: ordered (fcmp olt/ult/ord) driving integer or float select.
; fcmp.lt rD,rA,rB computes rB < rA (UG984 §5 reversed operands); to test
; LHS < RHS we use fcmp.gt which fires when RHS > LHS.
; +hard-float uses FCMP instructions; without it, compiler-rt comparison libcalls feed the branch.

; fcmp.lt rD, rA, rB computes rB < rA (UG984 §5 reversed operands).
; To test LHS < RHS we use fcmp.gt, which fires when RHS > LHS.
define i32 @fcmp_select_lt(float %a, float %b, i32 %x, i32 %y) {
;
; HW-LABEL: fcmp_select_lt:
; HW:       # %bb.0:
; HW-NEXT:    fcmp.gt r4, r5, r6
; HW-NEXT:    bneid r4, .LBB0_2
; HW-NEXT:    addk r3, r7, r0
; HW-NEXT:  .LBB0_1:
; HW-NEXT:    addk r3, r8, r0
; HW-NEXT:  .LBB0_2:
; HW-NEXT:    rtsd r15, 8
; HW-NEXT:    nop
;
; SOFT-LABEL: fcmp_select_lt:
; SOFT:       # %bb.0:
; SOFT-NEXT:    addik r1, r1, -12
; SOFT-NEXT:    swi r15, r1, 0
; SOFT-NEXT:    swi r19, r1, 8
; SOFT-NEXT:    swi r22, r1, 4
; SOFT-NEXT:    addk r22, r8, r0
; SOFT-NEXT:    bralid r15, __ltsf2
; SOFT-NEXT:    addk r19, r7, r0
; SOFT-NEXT:    addik r4, r0, 0
; SOFT-NEXT:    cmp r3, r4, r3
; SOFT-NEXT:    bltid r3, .LBB0_2
; SOFT-NEXT:    lwi r15, r1, 0
; SOFT-NEXT:  .LBB0_1:
; SOFT-NEXT:    addk r19, r22, r0
; SOFT-NEXT:  .LBB0_2:
; SOFT-NEXT:    addk r3, r19, r0
; SOFT-NEXT:    lwi r22, r1, 4
; SOFT-NEXT:    lwi r19, r1, 8
; SOFT-NEXT:    rtsd r15, 8
; SOFT-NEXT:    addik r1, r1, 12
  %cond = fcmp olt float %a, %b
  %r = select i1 %cond, i32 %x, i32 %y
  ret i32 %r
}

define i32 @fcmp_select_ult(float %a, float %b, i32 %x, i32 %y) {
;
; HW-LABEL: fcmp_select_ult:
; HW:       # %bb.0:
; HW-NEXT:    fcmp.gt r4, r5, r6
; HW-NEXT:    fcmp.un r5, r5, r6
; HW-NEXT:    or r4, r4, r5
; HW-NEXT:    bneid r4, .LBB1_2
; HW-NEXT:    addk r3, r7, r0
; HW-NEXT:  .LBB1_1:
; HW-NEXT:    addk r3, r8, r0
; HW-NEXT:  .LBB1_2:
; HW-NEXT:    rtsd r15, 8
; HW-NEXT:    nop
;
; SOFT-LABEL: fcmp_select_ult:
; SOFT:       # %bb.0:
; SOFT-NEXT:    addik r1, r1, -12
; SOFT-NEXT:    swi r15, r1, 0
; SOFT-NEXT:    swi r19, r1, 8
; SOFT-NEXT:    swi r22, r1, 4
; SOFT-NEXT:    addk r22, r8, r0
; SOFT-NEXT:    bralid r15, __gesf2
; SOFT-NEXT:    addk r19, r7, r0
; SOFT-NEXT:    addik r4, r0, 0
; SOFT-NEXT:    cmp r3, r4, r3
; SOFT-NEXT:    bltid r3, .LBB1_2
; SOFT-NEXT:    lwi r15, r1, 0
; SOFT-NEXT:  .LBB1_1:
; SOFT-NEXT:    addk r19, r22, r0
; SOFT-NEXT:  .LBB1_2:
; SOFT-NEXT:    addk r3, r19, r0
; SOFT-NEXT:    lwi r22, r1, 4
; SOFT-NEXT:    lwi r19, r1, 8
; SOFT-NEXT:    rtsd r15, 8
; SOFT-NEXT:    addik r1, r1, 12
  %cond = fcmp ult float %a, %b
  %r = select i1 %cond, i32 %x, i32 %y
  ret i32 %r
}

define i32 @fcmp_select_ord(float %a, float %b, i32 %x, i32 %y) {
;
; HW-LABEL: fcmp_select_ord:
; HW:       # %bb.0:
; HW-NEXT:    fcmp.un r4, r5, r6
; HW-NEXT:    beqid r4, .LBB2_2
; HW-NEXT:    addk r3, r7, r0
; HW-NEXT:  .LBB2_1:
; HW-NEXT:    addk r3, r8, r0
; HW-NEXT:  .LBB2_2:
; HW-NEXT:    rtsd r15, 8
; HW-NEXT:    nop
;
; SOFT-LABEL: fcmp_select_ord:
; SOFT:       # %bb.0:
; SOFT-NEXT:    addik r1, r1, -12
; SOFT-NEXT:    swi r15, r1, 0
; SOFT-NEXT:    swi r19, r1, 8
; SOFT-NEXT:    swi r22, r1, 4
; SOFT-NEXT:    addk r22, r8, r0
; SOFT-NEXT:    bralid r15, __unordsf2
; SOFT-NEXT:    addk r19, r7, r0
; SOFT-NEXT:    addik r4, r0, 0
; SOFT-NEXT:    rsubk r3, r3, r4
; SOFT-NEXT:    beqid r3, .LBB2_2
; SOFT-NEXT:    lwi r15, r1, 0
; SOFT-NEXT:  .LBB2_1:
; SOFT-NEXT:    addk r19, r22, r0
; SOFT-NEXT:  .LBB2_2:
; SOFT-NEXT:    addk r3, r19, r0
; SOFT-NEXT:    lwi r22, r1, 4
; SOFT-NEXT:    lwi r19, r1, 8
; SOFT-NEXT:    rtsd r15, 8
; SOFT-NEXT:    addik r1, r1, 12
  %cond = fcmp ord float %a, %b
  %r = select i1 %cond, i32 %x, i32 %y
  ret i32 %r
}

define float @fcmp_fselect_lt(float %a, float %b, float %x, float %y) {
;
; HW-LABEL: fcmp_fselect_lt:
; HW:       # %bb.0:
; HW-NEXT:    fcmp.gt r4, r5, r6
; HW-NEXT:    bneid r4, .LBB3_2
; HW-NEXT:    addk r3, r7, r0
; HW-NEXT:  .LBB3_1:
; HW-NEXT:    addk r3, r8, r0
; HW-NEXT:  .LBB3_2:
; HW-NEXT:    rtsd r15, 8
; HW-NEXT:    nop
;
; SOFT-LABEL: fcmp_fselect_lt:
; SOFT:       # %bb.0:
; SOFT-NEXT:    addik r1, r1, -12
; SOFT-NEXT:    swi r15, r1, 0
; SOFT-NEXT:    swi r19, r1, 8
; SOFT-NEXT:    swi r22, r1, 4
; SOFT-NEXT:    addk r22, r8, r0
; SOFT-NEXT:    bralid r15, __ltsf2
; SOFT-NEXT:    addk r19, r7, r0
; SOFT-NEXT:    addik r4, r0, 0
; SOFT-NEXT:    cmp r3, r4, r3
; SOFT-NEXT:    bltid r3, .LBB3_2
; SOFT-NEXT:    lwi r15, r1, 0
; SOFT-NEXT:  .LBB3_1:
; SOFT-NEXT:    addk r19, r22, r0
; SOFT-NEXT:  .LBB3_2:
; SOFT-NEXT:    addk r3, r19, r0
; SOFT-NEXT:    lwi r22, r1, 4
; SOFT-NEXT:    lwi r19, r1, 8
; SOFT-NEXT:    rtsd r15, 8
; SOFT-NEXT:    addik r1, r1, 12
  %cond = fcmp olt float %a, %b
  %r = select i1 %cond, float %x, float %y
  ret float %r
}
