; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=microblazeel -O2 < %s | FileCheck %s
; REQUIRES: microblaze-registered-target

; Indirect branch (computed goto) and blockaddress lowering.
; ISD::BRIND selects to BRAD (absolute register branch); the delay-slot filler
; may demote it to the no-delay BRA when the slot can't be filled.  A
; blockaddress materialised into a register goes through the Wrapper → ADDIK
; path (R_MICROBLAZE_32 against the .Ltmp block label).

; ── indirectbr through a table of block addresses ────────────────────────────
; The address-taken blocks get .Ltmp labels.
define i32 @f(i32 %x) {
; CHECK-LABEL: f:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addik r1, r1, -4
; CHECK-NEXT:    swi r15, r1, 0
; CHECK-NEXT:    bralid r15, __ashlsi3
; CHECK-NEXT:    addik r6, r0, 2
; CHECK-NEXT:    addik r4, r0, f.tab
; CHECK-NEXT:    lw r3, r3, r4
; CHECK-NEXT:    bra r3
; CHECK-NEXT:  .Ltmp0: # Block address taken
; CHECK-NEXT:  .LBB0_1: # %A
; CHECK-NEXT:    addik r3, r0, 1
; CHECK-NEXT:    bri .LBB0_4
; CHECK-NEXT:  .Ltmp1: # Block address taken
; CHECK-NEXT:  .LBB0_2: # %C
; CHECK-NEXT:    addik r3, r0, 3
; CHECK-NEXT:    bri .LBB0_4
; CHECK-NEXT:  .Ltmp2: # Block address taken
; CHECK-NEXT:  .LBB0_3: # %B
; CHECK-NEXT:    addik r3, r0, 2
; CHECK-NEXT:  .LBB0_4: # %A
; CHECK-NEXT:    lwi r15, r1, 0
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    addik r1, r1, 4
entry:
  %t = getelementptr inbounds [3 x ptr], ptr @f.tab, i32 0, i32 %x
  %a = load ptr, ptr %t
  indirectbr ptr %a, [label %A, label %B, label %C]
A:
  ret i32 1
B:
  ret i32 2
C:
  ret i32 3
}
@f.tab = internal constant [3 x ptr] [ptr blockaddress(@f, %A),
                                      ptr blockaddress(@f, %B),
                                      ptr blockaddress(@f, %C)]

; ── blockaddress materialised into a register (Wrapper → ADDIK) ──────────────
define ptr @take_addr() {
; CHECK-LABEL: take_addr:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .Ltmp3: # Block address taken
; CHECK-NEXT:  .LBB1_1: # %L
; CHECK-NEXT:    addik r3, r0, .Ltmp3
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    nop
entry:
  br label %L
L:
  ret ptr blockaddress(@take_addr, %L)
}

; The block-address table is emitted as data with R_MICROBLAZE_32 relocations
; against the .Ltmp block labels (comes after both functions in the output).
