; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=microblazeel < %s | FileCheck %s
; REQUIRES: microblaze-registered-target

; MicroBlaze interrupt_handler calling convention (cc73): save/restore the
; volatile registers used (R3-R12) plus the dedicated R17/R18, save/restore MSR
; (special reg 1) around them, and return through R14 with rtid.  The MSR scratch
; is R11 (forced saved).  Ported from the 2013 MBlaze backend (intr.ll).

@.str = private constant [4 x i8] c"hi\0A\00"
declare i32 @printf(ptr, ...)

; The IR alias is emitted by the AsmPrinter (no backend work needed).
@_interrupt_handler = alias void (), ptr @myintr

define cc73 void @myintr() nounwind noinline {
; Save volatiles + dedicated R17/R18 ...
; ... then MSR (special reg 1) via R11 scratch.
; CHECK-LABEL: myintr:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addik r1, r1, -56
; CHECK-NEXT:    swi r15, r1, 0
; CHECK-NEXT:    swi r3, r1, 52
; CHECK-NEXT:    swi r4, r1, 48
; CHECK-NEXT:    swi r5, r1, 44
; CHECK-NEXT:    swi r6, r1, 40
; CHECK-NEXT:    swi r7, r1, 36
; CHECK-NEXT:    swi r8, r1, 32
; CHECK-NEXT:    swi r9, r1, 28
; CHECK-NEXT:    swi r10, r1, 24
; CHECK-NEXT:    swi r11, r1, 20
; CHECK-NEXT:    swi r12, r1, 16
; CHECK-NEXT:    swi r17, r1, 12
; CHECK-NEXT:    swi r18, r1, 8
; CHECK-NEXT:    mfs r11, 1
; CHECK-NEXT:    addik r5, r0, .L.str
; CHECK-NEXT:    swi r11, r1, 4
; CHECK-NEXT:    bralid r15, printf
; CHECK-NEXT:    nop
; CHECK-NEXT:    lwi r11, r1, 4
; CHECK-NEXT:    mts 1, r11
; CHECK-NEXT:    lwi r18, r1, 8
; CHECK-NEXT:    lwi r17, r1, 12
; CHECK-NEXT:    lwi r12, r1, 16
; CHECK-NEXT:    lwi r11, r1, 20
; CHECK-NEXT:    lwi r10, r1, 24
; CHECK-NEXT:    lwi r9, r1, 28
; CHECK-NEXT:    lwi r8, r1, 32
; CHECK-NEXT:    lwi r7, r1, 36
; CHECK-NEXT:    lwi r6, r1, 40
; CHECK-NEXT:    lwi r5, r1, 44
; CHECK-NEXT:    lwi r4, r1, 48
; CHECK-NEXT:    lwi r3, r1, 52
; CHECK-NEXT:    lwi r15, r1, 0
; CHECK-NEXT:    rtid r14, 0
; CHECK-NEXT:    addik r1, r1, 56
entry:
  %c = call i32 (ptr, ...) @printf(ptr @.str)
  ret void
; Restore MSR first, then the saved registers, then rtid r14, 0.
}
