; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=microblazeel -mattr=+barrel-shift -O2 < %s | FileCheck %s
; RUN: llc -mtriple=microblazeel -mattr=+barrel-shift -relocation-model=pic -O2 < %s \
; RUN:   | FileCheck %s --check-prefix=PIC
; REQUIRES: microblaze-registered-target

; A dense switch lowers to a jump table: bounds-check, scale the index, load the
; target address from the .LJTI table, and BRIND (BRAD/BRA) to it.  The table is
; emitted as absolute MBB addresses (.long .LBB*, EK_BlockAddress → R_MICROBLAZE_32).
; +barrel-shift so the index*4 scale is a bsll, not an __ashlsi3 libcall.
;
; In PIC the base must be position-independent: it is the GOT base (r20) plus the
; .LJTI@GOTOFF link-time offset, and the entries are MBB - .LJTI label differences
; (EK_LabelDifference32), so no absolute or runtime relocation is needed.

; Bounds check against the largest case before indexing.
; Index scaled, table base materialised, entry loaded, indirect branch.
; The table: one absolute address per case.

; base = r20 + .LJTI0_0@gotoff; entries are MBB - .LJTI label differences.

declare void @sink(i32)

define void @sw(i32 %x) {
; CHECK-LABEL: sw:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addik r1, r1, -4
; CHECK-NEXT:    addik r3, r0, 7
; CHECK-NEXT:    swi r15, r1, 0
; CHECK-NEXT:    cmpu r3, r5, r3
; CHECK-NEXT:    blti r3, .LBB0_11
; CHECK-NEXT:  .LBB0_1: # %entry
; CHECK-NEXT:    bslli r3, r5, 2
; CHECK-NEXT:    addik r4, r0, .LJTI0_0
; CHECK-NEXT:    lw r3, r4, r3
; CHECK-NEXT:    bra r3
; CHECK-NEXT:  .LBB0_2: # %c0
; CHECK-NEXT:    addik r5, r0, 10
; CHECK-NEXT:    bri .LBB0_10
; CHECK-NEXT:  .LBB0_3: # %c4
; CHECK-NEXT:    addik r5, r0, 54
; CHECK-NEXT:    bri .LBB0_10
; CHECK-NEXT:  .LBB0_4: # %c2
; CHECK-NEXT:    addik r5, r0, 32
; CHECK-NEXT:    bri .LBB0_10
; CHECK-NEXT:  .LBB0_5: # %c3
; CHECK-NEXT:    addik r5, r0, 43
; CHECK-NEXT:    bri .LBB0_10
; CHECK-NEXT:  .LBB0_6: # %c7
; CHECK-NEXT:    addik r5, r0, 87
; CHECK-NEXT:    bri .LBB0_10
; CHECK-NEXT:  .LBB0_7: # %c1
; CHECK-NEXT:    addik r5, r0, 21
; CHECK-NEXT:    bri .LBB0_10
; CHECK-NEXT:  .LBB0_8: # %c5
; CHECK-NEXT:    addik r5, r0, 65
; CHECK-NEXT:    bri .LBB0_10
; CHECK-NEXT:  .LBB0_9: # %c6
; CHECK-NEXT:    addik r5, r0, 76
; CHECK-NEXT:  .LBB0_10: # %def
; CHECK-NEXT:    bralid r15, sink
; CHECK-NEXT:    nop
; CHECK-NEXT:  .LBB0_11: # %def
; CHECK-NEXT:    lwi r15, r1, 0
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    addik r1, r1, 4
;
; PIC-LABEL: sw:
; PIC:       # %bb.0: # %entry
; PIC-NEXT:    addik r1, r1, -4
; PIC-NEXT:    addik r3, r0, 7
; PIC-NEXT:    swi r15, r1, 0
; PIC-NEXT:    cmpu r3, r5, r3
; PIC-NEXT:    blti r3, .LBB0_11
; PIC-NEXT:  .LBB0_1: # %entry
; PIC-NEXT:    addik r4, r0, .LJTI0_0@gotoff
; PIC-NEXT:    bslli r3, r5, 2
; PIC-NEXT:    addk r4, r20, r4
; PIC-NEXT:    lw r3, r4, r3
; PIC-NEXT:    addk r3, r4, r3
; PIC-NEXT:    bra r3
; PIC-NEXT:  .LBB0_2: # %c0
; PIC-NEXT:    addik r5, r0, 10
; PIC-NEXT:    bri .LBB0_10
; PIC-NEXT:  .LBB0_3: # %c4
; PIC-NEXT:    addik r5, r0, 54
; PIC-NEXT:    bri .LBB0_10
; PIC-NEXT:  .LBB0_4: # %c2
; PIC-NEXT:    addik r5, r0, 32
; PIC-NEXT:    bri .LBB0_10
; PIC-NEXT:  .LBB0_5: # %c3
; PIC-NEXT:    addik r5, r0, 43
; PIC-NEXT:    bri .LBB0_10
; PIC-NEXT:  .LBB0_6: # %c7
; PIC-NEXT:    addik r5, r0, 87
; PIC-NEXT:    bri .LBB0_10
; PIC-NEXT:  .LBB0_7: # %c1
; PIC-NEXT:    addik r5, r0, 21
; PIC-NEXT:    bri .LBB0_10
; PIC-NEXT:  .LBB0_8: # %c5
; PIC-NEXT:    addik r5, r0, 65
; PIC-NEXT:    bri .LBB0_10
; PIC-NEXT:  .LBB0_9: # %c6
; PIC-NEXT:    addik r5, r0, 76
; PIC-NEXT:  .LBB0_10: # %def
; PIC-NEXT:    bralid r15, sink
; PIC-NEXT:    nop
; PIC-NEXT:  .LBB0_11: # %def
; PIC-NEXT:    lwi r15, r1, 0
; PIC-NEXT:    rtsd r15, 8
; PIC-NEXT:    addik r1, r1, 4
entry:
  switch i32 %x, label %def [
    i32 0, label %c0
    i32 1, label %c1
    i32 2, label %c2
    i32 3, label %c3
    i32 4, label %c4
    i32 5, label %c5
    i32 6, label %c6
    i32 7, label %c7
  ]
c0: tail call void @sink(i32 10) br label %def
c1: tail call void @sink(i32 21) br label %def
c2: tail call void @sink(i32 32) br label %def
c3: tail call void @sink(i32 43) br label %def
c4: tail call void @sink(i32 54) br label %def
c5: tail call void @sink(i32 65) br label %def
c6: tail call void @sink(i32 76) br label %def
c7: tail call void @sink(i32 87) br label %def
def:
  ret void
}
