; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=microblazeel < %s | FileCheck %s
; REQUIRES: microblaze-registered-target
; Loads: zero-extending (lbui/lhui) and sign-extending (sext8/sext16) byte and
; halfword, plus plain word (lwi).  Immediate offsets fold into the lwi addressing mode.

define i32 @load_i8_zext(ptr %p) {
; CHECK-LABEL: load_i8_zext:
; CHECK:       # %bb.0:
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    lbui r3, r5, 0
  %v = load i8, ptr %p
  %r = zext i8 %v to i32
  ret i32 %r
}

define i32 @load_i8_sext(ptr %p) {
; CHECK-LABEL: load_i8_sext:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lbui r3, r5, 0
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    sext8 r3, r3
  %v = load i8, ptr %p
  %r = sext i8 %v to i32
  ret i32 %r
}

define i32 @load_i16_zext(ptr %p) {
; CHECK-LABEL: load_i16_zext:
; CHECK:       # %bb.0:
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    lhui r3, r5, 0
  %v = load i16, ptr %p
  %r = zext i16 %v to i32
  ret i32 %r
}

define i32 @load_i16_sext(ptr %p) {
; CHECK-LABEL: load_i16_sext:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lhui r3, r5, 0
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    sext16 r3, r3
  %v = load i16, ptr %p
  %r = sext i16 %v to i32
  ret i32 %r
}

define i32 @load_i32(ptr %p) {
; CHECK-LABEL: load_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    lwi r3, r5, 0
  %r = load i32, ptr %p
  ret i32 %r
}

; Immediate offset folds into lwi addressing mode (offset*4 → byte offset).
define i32 @load_i32_offset(ptr %p) {
; CHECK-LABEL: load_i32_offset:
; CHECK:       # %bb.0:
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    lwi r3, r5, 8
  %q = getelementptr i32, ptr %p, i32 2
  %r = load i32, ptr %q
  ret i32 %r
}
