; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; Integer multiply always lowers to the hardware mul instruction.
;
; The 2013 MBlaze backend gated mul emission on a +mul feature flag.
; Our backend has no such flag: mul rD, rA, rB is always selected,
; matching hardware targets with C_USE_HW_MUL=1 (the common case for
; Vivado-generated MicroBlaze cores). For cores without a multiplier
; a soft-multiply library would be needed at link time — we do not model
; this at the IR level.
;
; Per UG984 Ch.5: mul rD, rA, rB  — rD := rA * rB (lower 32 bits)
;
; RUN: llc -mtriple=microblazeel-unknown-elf < %s | FileCheck %s
; REQUIRES: microblaze-registered-target
define i32 @mul_i32(i32 %a, i32 %b) {
; mul lands in the rtsd delay slot
; CHECK-LABEL: mul_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    mul r3, r5, r6
    %r = mul i32 %a, %b
    ret i32 %r
}

; Narrower types are promoted to i32 before multiplying.

define i16 @mul_i16(i16 %a, i16 %b) {
; CHECK-LABEL: mul_i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    mul r3, r5, r6
    %r = mul i16 %a, %b
    ret i16 %r
}

define i8 @mul_i8(i8 %a, i8 %b) {
; CHECK-LABEL: mul_i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    mul r3, r5, r6
    %r = mul i8 %a, %b
    ret i8 %r
}
