; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; Tests for PCMPEQ, PCMPNE, and CLZ instruction selection gating on
; +pattern-compare.  Without the feature the backend must expand these to
; software sequences; with it, single instructions are required.
;
; RUN: llc -mtriple=microblazeel -mattr=+pattern-compare %s -o - | FileCheck %s --check-prefix=FEAT
; RUN: llc -mtriple=microblazeel -mattr=-pattern-compare %s -o - | FileCheck %s --check-prefix=NOFEAT
; REQUIRES: microblaze-registered-target

; ── PCMPEQ: integer equality ─────────────────────────────────────────────────

define i32 @eq_i32(i32 %a, i32 %b) {
; FEAT-LABEL: eq_i32:
; FEAT:       # %bb.0:
; FEAT-NEXT:    rtsd r15, 8
; FEAT-NEXT:    pcmpeq r3, r5, r6
;
; NOFEAT-LABEL: eq_i32:
; NOFEAT:       # %bb.0:
; NOFEAT-NEXT:    rsubk r3, r6, r5
; NOFEAT-NEXT:    beqi r3, .LBB0_2
; NOFEAT-NEXT:  .LBB0_1:
; NOFEAT-NEXT:    rtsd r15, 8
; NOFEAT-NEXT:    addik r3, r0, 0
; NOFEAT-NEXT:  .LBB0_2:
; NOFEAT-NEXT:    rtsd r15, 8
; NOFEAT-NEXT:    addik r3, r0, 1
  %r = icmp eq i32 %a, %b
  %z = zext i1 %r to i32
  ret i32 %z
}

; ── PCMPNE: integer inequality ────────────────────────────────────────────────

define i32 @ne_i32(i32 %a, i32 %b) {
; FEAT-LABEL: ne_i32:
; FEAT:       # %bb.0:
; FEAT-NEXT:    rtsd r15, 8
; FEAT-NEXT:    pcmpne r3, r5, r6
;
; NOFEAT-LABEL: ne_i32:
; NOFEAT:       # %bb.0:
; NOFEAT-NEXT:    rsubk r3, r6, r5
; NOFEAT-NEXT:    bnei r3, .LBB1_2
; NOFEAT-NEXT:  .LBB1_1:
; NOFEAT-NEXT:    rtsd r15, 8
; NOFEAT-NEXT:    addik r3, r0, 0
; NOFEAT-NEXT:  .LBB1_2:
; NOFEAT-NEXT:    rtsd r15, 8
; NOFEAT-NEXT:    addik r3, r0, 1
  %r = icmp ne i32 %a, %b
  %z = zext i1 %r to i32
  ret i32 %z
}

; ── CLZ: count leading zeros (i1 false = may-be-zero form) ───────────────────

define i32 @clz_maybedef(i32 %x) {
; FEAT-LABEL: clz_maybedef:
; FEAT:       # %bb.0:
; FEAT-NEXT:    beqi r5, .LBB2_2
; FEAT-NEXT:  .LBB2_1: # %cond.false
; FEAT-NEXT:    rtsd r15, 8
; FEAT-NEXT:    clz r3, r5
; FEAT-NEXT:  .LBB2_2:
; FEAT-NEXT:    rtsd r15, 8
; FEAT-NEXT:    addik r3, r0, 32
;
; NOFEAT-LABEL: clz_maybedef:
; NOFEAT:       # %bb.0:
; NOFEAT-NEXT:    addik r1, r1, -24
; NOFEAT-NEXT:    swi r15, r1, 4
; NOFEAT-NEXT:    swi r19, r1, 20
; NOFEAT-NEXT:    swi r22, r1, 16
; NOFEAT-NEXT:    swi r23, r1, 12
; NOFEAT-NEXT:    swi r24, r1, 8
; NOFEAT-NEXT:    beqi r5, .LBB2_2
; NOFEAT-NEXT:  .LBB2_1: # %cond.false
; NOFEAT-NEXT:    addik r23, r0, 1
; NOFEAT-NEXT:    addk r19, r5, r0
; NOFEAT-NEXT:    bralid r15, __lshrsi3
; NOFEAT-NEXT:    addk r6, r23, r0
; NOFEAT-NEXT:    or r22, r19, r3
; NOFEAT-NEXT:    addik r19, r0, 2
; NOFEAT-NEXT:    addk r5, r22, r0
; NOFEAT-NEXT:    bralid r15, __lshrsi3
; NOFEAT-NEXT:    addk r6, r19, r0
; NOFEAT-NEXT:    or r24, r22, r3
; NOFEAT-NEXT:    addik r22, r0, 4
; NOFEAT-NEXT:    addk r5, r24, r0
; NOFEAT-NEXT:    bralid r15, __lshrsi3
; NOFEAT-NEXT:    addk r6, r22, r0
; NOFEAT-NEXT:    or r24, r24, r3
; NOFEAT-NEXT:    addik r6, r0, 8
; NOFEAT-NEXT:    bralid r15, __lshrsi3
; NOFEAT-NEXT:    addk r5, r24, r0
; NOFEAT-NEXT:    or r24, r24, r3
; NOFEAT-NEXT:    addik r6, r0, 16
; NOFEAT-NEXT:    bralid r15, __lshrsi3
; NOFEAT-NEXT:    addk r5, r24, r0
; NOFEAT-NEXT:    or r3, r24, r3
; NOFEAT-NEXT:    addk r6, r23, r0
; NOFEAT-NEXT:    xori r24, r3, -1
; NOFEAT-NEXT:    bralid r15, __lshrsi3
; NOFEAT-NEXT:    addk r5, r24, r0
; NOFEAT-NEXT:    addik r4, r0, 1431655765
; NOFEAT-NEXT:    addik r23, r0, 858993459
; NOFEAT-NEXT:    addk r6, r19, r0
; NOFEAT-NEXT:    and r3, r3, r4
; NOFEAT-NEXT:    rsubk r5, r3, r24
; NOFEAT-NEXT:    bralid r15, __lshrsi3
; NOFEAT-NEXT:    and r24, r5, r23
; NOFEAT-NEXT:    and r3, r3, r23
; NOFEAT-NEXT:    addk r6, r22, r0
; NOFEAT-NEXT:    addk r19, r24, r3
; NOFEAT-NEXT:    bralid r15, __lshrsi3
; NOFEAT-NEXT:    addk r5, r19, r0
; NOFEAT-NEXT:    addk r3, r19, r3
; NOFEAT-NEXT:    addik r4, r0, 252645135
; NOFEAT-NEXT:    addik r6, r0, 24
; NOFEAT-NEXT:    and r3, r3, r4
; NOFEAT-NEXT:    addik r4, r0, 16843009
; NOFEAT-NEXT:    bralid r15, __lshrsi3
; NOFEAT-NEXT:    mul r5, r3, r4
; NOFEAT-NEXT:    bri .LBB2_3
; NOFEAT-NEXT:  .LBB2_2:
; NOFEAT-NEXT:    addik r3, r0, 32
; NOFEAT-NEXT:  .LBB2_3: # %cond.end
; NOFEAT-NEXT:    lwi r24, r1, 8
; NOFEAT-NEXT:    lwi r23, r1, 12
; NOFEAT-NEXT:    lwi r22, r1, 16
; NOFEAT-NEXT:    lwi r19, r1, 20
; NOFEAT-NEXT:    lwi r15, r1, 4
; NOFEAT-NEXT:    rtsd r15, 8
; NOFEAT-NEXT:    addik r1, r1, 24
  %r = call i32 @llvm.ctlz.i32(i32 %x, i1 false)
  ret i32 %r
}

; ── CLZ: count leading zeros (i1 true = poison-if-zero form) ─────────────────

define i32 @clz_poisondef(i32 %x) {
; FEAT-LABEL: clz_poisondef:
; FEAT:       # %bb.0:
; FEAT-NEXT:    rtsd r15, 8
; FEAT-NEXT:    clz r3, r5
;
; NOFEAT-LABEL: clz_poisondef:
; NOFEAT:       # %bb.0:
; NOFEAT-NEXT:    addik r1, r1, -24
; NOFEAT-NEXT:    swi r15, r1, 4
; NOFEAT-NEXT:    swi r19, r1, 20
; NOFEAT-NEXT:    swi r22, r1, 16
; NOFEAT-NEXT:    swi r23, r1, 12
; NOFEAT-NEXT:    addik r23, r0, 1
; NOFEAT-NEXT:    swi r24, r1, 8
; NOFEAT-NEXT:    addk r19, r5, r0
; NOFEAT-NEXT:    bralid r15, __lshrsi3
; NOFEAT-NEXT:    addk r6, r23, r0
; NOFEAT-NEXT:    or r22, r19, r3
; NOFEAT-NEXT:    addik r19, r0, 2
; NOFEAT-NEXT:    addk r5, r22, r0
; NOFEAT-NEXT:    bralid r15, __lshrsi3
; NOFEAT-NEXT:    addk r6, r19, r0
; NOFEAT-NEXT:    or r24, r22, r3
; NOFEAT-NEXT:    addik r22, r0, 4
; NOFEAT-NEXT:    addk r5, r24, r0
; NOFEAT-NEXT:    bralid r15, __lshrsi3
; NOFEAT-NEXT:    addk r6, r22, r0
; NOFEAT-NEXT:    or r24, r24, r3
; NOFEAT-NEXT:    addik r6, r0, 8
; NOFEAT-NEXT:    bralid r15, __lshrsi3
; NOFEAT-NEXT:    addk r5, r24, r0
; NOFEAT-NEXT:    or r24, r24, r3
; NOFEAT-NEXT:    addik r6, r0, 16
; NOFEAT-NEXT:    bralid r15, __lshrsi3
; NOFEAT-NEXT:    addk r5, r24, r0
; NOFEAT-NEXT:    or r3, r24, r3
; NOFEAT-NEXT:    addk r6, r23, r0
; NOFEAT-NEXT:    xori r24, r3, -1
; NOFEAT-NEXT:    bralid r15, __lshrsi3
; NOFEAT-NEXT:    addk r5, r24, r0
; NOFEAT-NEXT:    addik r4, r0, 1431655765
; NOFEAT-NEXT:    addik r23, r0, 858993459
; NOFEAT-NEXT:    addk r6, r19, r0
; NOFEAT-NEXT:    and r3, r3, r4
; NOFEAT-NEXT:    rsubk r5, r3, r24
; NOFEAT-NEXT:    bralid r15, __lshrsi3
; NOFEAT-NEXT:    and r24, r5, r23
; NOFEAT-NEXT:    and r3, r3, r23
; NOFEAT-NEXT:    addk r6, r22, r0
; NOFEAT-NEXT:    addk r19, r24, r3
; NOFEAT-NEXT:    bralid r15, __lshrsi3
; NOFEAT-NEXT:    addk r5, r19, r0
; NOFEAT-NEXT:    addk r3, r19, r3
; NOFEAT-NEXT:    addik r4, r0, 252645135
; NOFEAT-NEXT:    addik r6, r0, 24
; NOFEAT-NEXT:    and r3, r3, r4
; NOFEAT-NEXT:    addik r4, r0, 16843009
; NOFEAT-NEXT:    bralid r15, __lshrsi3
; NOFEAT-NEXT:    mul r5, r3, r4
; NOFEAT-NEXT:    lwi r24, r1, 8
; NOFEAT-NEXT:    lwi r23, r1, 12
; NOFEAT-NEXT:    lwi r22, r1, 16
; NOFEAT-NEXT:    lwi r19, r1, 20
; NOFEAT-NEXT:    lwi r15, r1, 4
; NOFEAT-NEXT:    rtsd r15, 8
; NOFEAT-NEXT:    addik r1, r1, 24
  %r = call i32 @llvm.ctlz.i32(i32 %x, i1 true)
  ret i32 %r
}

declare i32 @llvm.ctlz.i32(i32, i1)
