; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=microblazeel-unknown-elf -relocation-model=pic -O1 < %s | FileCheck %s --check-prefix=PIC
; RUN: llc -mtriple=microblazeel-unknown-elf -relocation-model=static -O1 < %s | FileCheck %s --check-prefix=STATIC
; REQUIRES: microblaze-registered-target
; In PIC mode, global variable addresses come from the GOT via R20 (the GOT base register).
; In static mode, global addresses are materialised directly with addik.

@extern_int = external global i32
@extern_b   = external global i32

; get_global is a 2-instruction function; the delay slot filler hoists lwi into rtsd's slot.
define i32 @get_global() {
; PIC-LABEL: get_global:
; PIC:       # %bb.0:
; PIC-NEXT:    la_got r3, extern_int@got
; PIC-NEXT:    rtsd r15, 8
; PIC-NEXT:    lwi r3, r3, 0
;
; STATIC-LABEL: get_global:
; STATIC:       # %bb.0:
; STATIC-NEXT:    addik r3, r0, extern_int
; STATIC-NEXT:    rtsd r15, 8
; STATIC-NEXT:    lwi r3, r3, 0
  %v = load i32, ptr @extern_int, align 4
  ret i32 %v
}

define i32 @sum_globals() {
; PIC-LABEL: sum_globals:
; PIC:       # %bb.0:
; PIC-NEXT:    la_got r3, extern_b@got
; PIC-NEXT:    lwi r3, r3, 0
; PIC-NEXT:    la_got r4, extern_int@got
; PIC-NEXT:    lwi r4, r4, 0
; PIC-NEXT:    rtsd r15, 8
; PIC-NEXT:    addk r3, r4, r3
;
; STATIC-LABEL: sum_globals:
; STATIC:       # %bb.0:
; STATIC-NEXT:    addik r3, r0, extern_b
; STATIC-NEXT:    lwi r3, r3, 0
; STATIC-NEXT:    addik r4, r0, extern_int
; STATIC-NEXT:    lwi r4, r4, 0
; STATIC-NEXT:    rtsd r15, 8
; STATIC-NEXT:    addk r3, r4, r3
  %a = load i32, ptr @extern_int, align 4
  %b = load i32, ptr @extern_b, align 4
  %r = add i32 %a, %b
  ret i32 %r
}
