; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=microblazeel < %s | FileCheck %s
; REQUIRES: microblaze-registered-target

; Sign-extension uses SEXT8/SEXT16 instructions (UG984 §5).
; Zero-extension via AND with immediate mask.

define i32 @sext8(i8 %a) {
; CHECK-LABEL: sext8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    sext8 r3, r5
  %r = sext i8 %a to i32
  ret i32 %r
}

define i32 @sext16(i16 %a) {
; CHECK-LABEL: sext16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    sext16 r3, r5
  %r = sext i16 %a to i32
  ret i32 %r
}

; Zero-extend i8: AND with 0xFF = andi r3, r5, 255
define i32 @zext8(i8 %a) {
; CHECK-LABEL: zext8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    andi r3, r5, 255
  %r = zext i8 %a to i32
  ret i32 %r
}

; Zero-extend i16: 65535 > signed-16-bit range → addik+and
define i32 @zext16(i16 %a) {
; CHECK-LABEL: zext16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addik r3, r0, 65535
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    and r3, r5, r3
  %r = zext i16 %a to i32
  ret i32 %r
}
