; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=microblazeel -mattr=+barrel-shift < %s | FileCheck %s
; REQUIRES: microblaze-registered-target

; Register-form shifts (variable shift amount) → BSRL/BSRA/BSLL
; The delay slot filler hoists the barrel-shift into rtsd's delay slot.

define i32 @srl_reg(i32 %a, i32 %b) {
; CHECK-LABEL: srl_reg:
; CHECK:       # %bb.0:
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    bsrl r3, r5, r6
  %r = lshr i32 %a, %b
  ret i32 %r
}

define i32 @sra_reg(i32 %a, i32 %b) {
; CHECK-LABEL: sra_reg:
; CHECK:       # %bb.0:
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    bsra r3, r5, r6
  %r = ashr i32 %a, %b
  ret i32 %r
}

define i32 @shl_reg(i32 %a, i32 %b) {
; CHECK-LABEL: shl_reg:
; CHECK:       # %bb.0:
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    bsll r3, r5, r6
  %r = shl i32 %a, %b
  ret i32 %r
}

; Immediate-form shifts (constant shift amount) → BSRLI/BSRAI/BSLLI

define i32 @srl_imm(i32 %a) {
; CHECK-LABEL: srl_imm:
; CHECK:       # %bb.0:
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    bsrli r3, r5, 5
  %r = lshr i32 %a, 5
  ret i32 %r
}

; ashr by 1 uses the dedicated single-bit 'sra' instruction rather than bsrai.
; sra writes MSR.C so the delay slot filler cannot hoist it; nop fills the slot.
define i32 @sra_imm(i32 %a) {
; CHECK-LABEL: sra_imm:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sra r3, r5
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    nop
  %r = ashr i32 %a, 1
  ret i32 %r
}

define i32 @shl_imm(i32 %a) {
; CHECK-LABEL: shl_imm:
; CHECK:       # %bb.0:
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    bslli r3, r5, 3
  %r = shl i32 %a, 3
  ret i32 %r
}

; Shift-by-31 (maximum uimm5 value)
define i32 @srl_31(i32 %a) {
; CHECK-LABEL: srl_31:
; CHECK:       # %bb.0:
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    bsrli r3, r5, 31
  %r = lshr i32 %a, 31
  ret i32 %r
}

; Shift-by-1 (minimum nonzero)
define i32 @shl_1(i32 %a) {
; CHECK-LABEL: shl_1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    bslli r3, r5, 1
  %r = shl i32 %a, 1
  ret i32 %r
}
