; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=microblazeel < %s | FileCheck %s
; REQUIRES: microblaze-registered-target
; Stores: byte (sbi), halfword (shi), word (swi).
; The store has side effects so the delay slot filler inserts nop after rtsd.

define void @store_i8(ptr %p, i8 %v) {
; CHECK-LABEL: store_i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sbi r6, r5, 0
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    nop
  store i8 %v, ptr %p
  ret void
}

define void @store_i16(ptr %p, i16 %v) {
; CHECK-LABEL: store_i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    shi r6, r5, 0
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    nop
  store i16 %v, ptr %p
  ret void
}

define void @store_i32(ptr %p, i32 %v) {
; CHECK-LABEL: store_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    swi r6, r5, 0
; CHECK-NEXT:    rtsd r15, 8
; CHECK-NEXT:    nop
  store i32 %v, ptr %p
  ret void
}
